export const SAVE_DECK_REQUEST = "SAVE_DECK_REQUEST";
export const SAVE_DECK_FAILED = "SAVE_DECK_FAILED";
export const SAVE_DECK_SUCCESS = "SAVE_DECK_SUCCESS";

export const GET_DECKS_REQUEST = "GET_DECKS_REQUEST";
export const GET_DECKS_FAILED = "GET_DECKS_FAILED";
export const GET_DECKS_SUCCESS = "GET_DECKS_SUCCESS";

export const SAVE_CARD_REQUEST = "SAVE_CARD_REQUEST";
export const SAVE_CARD_FAILED = "SAVE_CARD_FAILED";
export const SAVE_CARD_SUCCESS = "SAVE_CARD_SUCCESS";

export const MARK_GUESS_REQUEST = "MARK_GUESS_REQUEST";
export const MARK_GUESS_FAILED = "MARK_GUESS_FAILED";
export const MARK_GUESS_SUCCESS = "MARK_GUESS_SUCCESS";

export const UNMARK_QUESTION_REQUEST = "UNMARK_QUESTION_REQUEST";
export const UNMARK_QUESTION_FAILED = "UNMARK_QUESTION_FAILED";
export const UNMARK_QUESTION_SUCCESS = "UNMARK_QUESTION_SUCCESS";
