export const SAVE_DECK_REQUEST = "SAVE_DECK_REQUEST";
export const SAVE_DECK_FAILED = "SAVE_DECK_FAILED";
export const SAVE_DECK_SUCCESS = "SAVE_DECK_SUCCESS";

export const GET_DECKS_REQUEST = "GET_DECKS_REQUEST";
export const GET_DECKS_FAILED = "GET_DECKS_FAILED";
export const GET_DECKS_SUCCESS = "GET_DECKS_SUCCESS";
